/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appMobaRouteRouteImport } from './routes/(app)/moba/route'
import { Route as appMobaHeroesRouteRouteImport } from './routes/(app)/moba/heroes/route'
import { Route as appMobaGuidesRouteRouteImport } from './routes/(app)/moba/guides/route'
import { Route as appMobaBuildsRouteRouteImport } from './routes/(app)/moba/builds/route'
import { Route as appMobaItemsIndexRouteImport } from './routes/(app)/moba/items/index'
import { Route as appMobaItemsItemIdRouteImport } from './routes/(app)/moba/items/$itemId'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appMobaRouteRoute = appMobaRouteRouteImport.update({
  id: '/moba',
  path: '/moba',
  getParentRoute: () => appRouteRoute,
} as any)
const appMobaHeroesRouteRoute = appMobaHeroesRouteRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => appMobaRouteRoute,
} as any)
const appMobaGuidesRouteRoute = appMobaGuidesRouteRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => appMobaRouteRoute,
} as any)
const appMobaBuildsRouteRoute = appMobaBuildsRouteRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => appMobaRouteRoute,
} as any)
const appMobaItemsIndexRoute = appMobaItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => appMobaRouteRoute,
} as any)
const appMobaItemsItemIdRoute = appMobaItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => appMobaRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRoute
  '/moba': typeof appMobaRouteRouteWithChildren
  '/': typeof appIndexRoute
  '/moba/builds': typeof appMobaBuildsRouteRoute
  '/moba/guides': typeof appMobaGuidesRouteRoute
  '/moba/heroes': typeof appMobaHeroesRouteRoute
  '/moba/items/$itemId': typeof appMobaItemsItemIdRoute
  '/moba/items': typeof appMobaItemsIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteRoute
  '/moba': typeof appMobaRouteRouteWithChildren
  '/': typeof appIndexRoute
  '/moba/builds': typeof appMobaBuildsRouteRoute
  '/moba/guides': typeof appMobaGuidesRouteRoute
  '/moba/heroes': typeof appMobaHeroesRouteRoute
  '/moba/items/$itemId': typeof appMobaItemsItemIdRoute
  '/moba/items': typeof appMobaItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/admin': typeof AdminRouteRoute
  '/(app)/moba': typeof appMobaRouteRouteWithChildren
  '/(app)/': typeof appIndexRoute
  '/(app)/moba/builds': typeof appMobaBuildsRouteRoute
  '/(app)/moba/guides': typeof appMobaGuidesRouteRoute
  '/(app)/moba/heroes': typeof appMobaHeroesRouteRoute
  '/(app)/moba/items/$itemId': typeof appMobaItemsItemIdRoute
  '/(app)/moba/items/': typeof appMobaItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/moba'
    | '/'
    | '/moba/builds'
    | '/moba/guides'
    | '/moba/heroes'
    | '/moba/items/$itemId'
    | '/moba/items'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/moba'
    | '/'
    | '/moba/builds'
    | '/moba/guides'
    | '/moba/heroes'
    | '/moba/items/$itemId'
    | '/moba/items'
  id:
    | '__root__'
    | '/(app)'
    | '/admin'
    | '/(app)/moba'
    | '/(app)/'
    | '/(app)/moba/builds'
    | '/(app)/moba/guides'
    | '/(app)/moba/heroes'
    | '/(app)/moba/items/$itemId'
    | '/(app)/moba/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/moba': {
      id: '/(app)/moba'
      path: '/moba'
      fullPath: '/moba'
      preLoaderRoute: typeof appMobaRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/moba/heroes': {
      id: '/(app)/moba/heroes'
      path: '/heroes'
      fullPath: '/moba/heroes'
      preLoaderRoute: typeof appMobaHeroesRouteRouteImport
      parentRoute: typeof appMobaRouteRoute
    }
    '/(app)/moba/guides': {
      id: '/(app)/moba/guides'
      path: '/guides'
      fullPath: '/moba/guides'
      preLoaderRoute: typeof appMobaGuidesRouteRouteImport
      parentRoute: typeof appMobaRouteRoute
    }
    '/(app)/moba/builds': {
      id: '/(app)/moba/builds'
      path: '/builds'
      fullPath: '/moba/builds'
      preLoaderRoute: typeof appMobaBuildsRouteRouteImport
      parentRoute: typeof appMobaRouteRoute
    }
    '/(app)/moba/items/': {
      id: '/(app)/moba/items/'
      path: '/items'
      fullPath: '/moba/items'
      preLoaderRoute: typeof appMobaItemsIndexRouteImport
      parentRoute: typeof appMobaRouteRoute
    }
    '/(app)/moba/items/$itemId': {
      id: '/(app)/moba/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/moba/items/$itemId'
      preLoaderRoute: typeof appMobaItemsItemIdRouteImport
      parentRoute: typeof appMobaRouteRoute
    }
  }
}

interface appMobaRouteRouteChildren {
  appMobaBuildsRouteRoute: typeof appMobaBuildsRouteRoute
  appMobaGuidesRouteRoute: typeof appMobaGuidesRouteRoute
  appMobaHeroesRouteRoute: typeof appMobaHeroesRouteRoute
  appMobaItemsItemIdRoute: typeof appMobaItemsItemIdRoute
  appMobaItemsIndexRoute: typeof appMobaItemsIndexRoute
}

const appMobaRouteRouteChildren: appMobaRouteRouteChildren = {
  appMobaBuildsRouteRoute: appMobaBuildsRouteRoute,
  appMobaGuidesRouteRoute: appMobaGuidesRouteRoute,
  appMobaHeroesRouteRoute: appMobaHeroesRouteRoute,
  appMobaItemsItemIdRoute: appMobaItemsItemIdRoute,
  appMobaItemsIndexRoute: appMobaItemsIndexRoute,
}

const appMobaRouteRouteWithChildren = appMobaRouteRoute._addFileChildren(
  appMobaRouteRouteChildren,
)

interface appRouteRouteChildren {
  appMobaRouteRoute: typeof appMobaRouteRouteWithChildren
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appMobaRouteRoute: appMobaRouteRouteWithChildren,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
