from decouple import config

SESSION_MIDDLEWARE = config("SESSION_MIDDLEWARE")

OAUTH_VK_CLIENT_ID = config("OAUTH_VK_CLIENT_ID")
OAUTH_VK_CLIENT_SECRET = config("OAUTH_VK_CLIENT_SECRET")
OAUTH_VK_CLIENT_SECRET_SERVICE = config("OAUTH_VK_CLIENT_SECRET_SERVICE")
OAUTH_VK_CLIENT_REDIRECT_URI = config("OAUTH_VK_CLIENT_REDIRECT_URI")

POSTGRES_HOST = config("POSTGRES_HOST")
POSTGRES_PORT = config("POSTGRES_PORT")
POSTGRES_DB = config("POSTGRES_DB")
POSTGRES_USER = config("POSTGRES_USER")
POSTGRES_PASSWORD = config("POSTGRES_PASSWORD")
POSTGRES_DSN = f"postgres://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
